version: '3.8'

services:
  backend:
    container_name: idls_app_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
      - "5001:5001/udp"
      - "14550:14550/udp"
      - "14551:14551/udp"
    volumes:
      - ./:/idls_app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - udp_network

  frontend:
    container_name: idls_app_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/idls_app/frontend
      - node_modules:/idls_app/frontend/node_modules

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/frontend/node_modules
      o: bind

networks:
  udp_network:
    external: true
    name: udp_network