services:

  development:
    container_name: gcs_dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./:/gcs
    working_dir: /gcs
    tty: true
    stdin_open: true
    command: sh -c "sleep infinity"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/gcs
    networks:
      - udp_network

  backend:
    container_name: gcs_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
      - "5001:5001/udp"
      - "14610:14610/udp"
      - "14611:14611/udp"
    volumes:
      - ./:/gcs
    working_dir: /gcs
    tty: true
    stdin_open: true
    command: sh -c "exec uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /gcs/backend"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/gcs
      - WATCHFILES_FORCE_POLLING=true
      - WATCHFILES_POLL_DELAY_MS=300
    networks:
      - udp_network

  frontend:
    container_name: gcs_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/gcs/frontend
      - node_modules:/gcs/frontend/node_modules
    working_dir: /gcs/frontend
    stdin_open: true
    command: sh -c "npm start"
    networks:
      - udp_network

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/frontend/node_modules
      o: bind

networks:
  udp_network:
    external: true
    name: udp_network
