services:
  backend:
    container_name: idls_app_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
      - "5001:5001/udp"
      - "14610:14610/udp"
      - "14611:14611/udp"
    volumes:
      - ./:/idls_app
    tty: true
    stdin_open: true
    # コンテナ起動時に自動でFastAPIサーバを起動したい場合は、下記のコメントアウトを外してください。
    # command: sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload & sleep infinity"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/idls_app
    networks:
      - udp_network

  frontend:
    container_name: idls_app_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/idls_app/frontend:cached
      - node_modules:/idls_app/frontend/node_modules
    networks:
      - udp_network

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/frontend/node_modules
      o: bind

networks:
  udp_network:
    external: true
    name: udp_network
